-- Adição de ID sequencial para eventos (mais fácil de lembrar)
-- Rodar este SQL no editor de SQL do Supabase ou via CLI se necessário.

ALTER TABLE public.events 
ADD COLUMN seq_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Opcional: Criar um índice para buscas rápidas
CREATE INDEX idx_events_seq_id ON public.events(seq_id);

-- Para eventos já existentes, a coluna seq_id será populada automaticamente se for IDENTITY.
